### PR TITLE
Add auto tests

### PR DESCRIPTION
**Pull request by andrewjaykeller**

### CODE REVIEW

**Comment by andrewjaykeller** [comment]
I can't get the disconnect function working yet, this is not ready for a merge but I wanted to see if you could figure out the fix. There is a weird issue going on with listeners.

**Comment by andrewjaykeller** [comment]
@baffo32 Karl, I still cannot get this disconnect function to properly with out messing up the other functions. Could you lend a set of eyes on this?

If you mark the disconnect test on line 506 as pending (`xit`) then everything passes. https://github.com/baffo32/OpenBCI_NodeJS/pull/1/files#diff-c1d26d8dbab01a3b12bf4b04e3c443c0R560

However if you don't then a later on there is a problem where the tests are sending bad samples and such. It has to do something with the streaming and listeners.

**Comment by andrewjaykeller** [comment]
Whoa looking at travis, it appears this is only an issue when running node 6.3... scratching my head for real now https://travis-ci.org/aj-ptw/OpenBCI_NodeJS/builds/160211768

EDIT: actually no, it's broken in all

**Comment by baffo32** [comment]
AJ thank you for looking at this.  I am in the hospital and review is challenging.  Please don't worry about it unless it interests you.

**Comment by andrewjaykeller** [comment]
Karl, I'm sorry to hear you are in the hospital and hope you a speedy recovery! I think this is a cool feature that many would benefit from. Being that it has pretty big consequences to break stuff I don't want to rush it!

**Comment by baffo32** [comment]
I'm maybe 2/3rds through reviewing, comprehending, and ensuring correctness of this.  I plan to finish it within a couple weeks at the longest, perhaps soon.

**Comment by andrewjaykeller** [comment]
@baffo32 awesome!

**Pull request merged**
